Styling
gsmalik030/bookstore pull request #5
Opened 2023-03-02 16:46 UTC by gsmalik030

In this PR:

I added styling for my project.

2023-03-02 17:07 UTC, roshan-bajgain requested changes
Hi @gsmalik030, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Professional README file. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 17:07 UTC, roshan-bajgain commented on src/components/styles/book.css
> +}
- [ ] According to the project requirement styling is exactly the same as provided on the Zeplin. You need to make a small change on your styling that is color for `book and categories` on the navbar.
- [ ] Kindly updated the color of `Updated progress` and input for the button. See the image below for reference
- [ ] Also make sure to add the same logo that is on the right. For this, you can use the credentials from project requirement to login
### Your design
![his](https://user-images.githubusercontent.com/81727988/222499825-1af480ce-62db-43b9-ac7e-2cfe92542d9f.png)


### Original design
![figma](https://user-images.githubusercontent.com/81727988/222499892-84c939b7-6d58-4fea-aeef-f2a79cde99ac.png)

2023-03-03 04:33 UTC, mahbubul14 requested changes
Hi @gsmalik030,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Fixed bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-03 04:33 UTC, mahbubul14 commented on src/components/Navbar.jsx
> +        <li><Link to="/categories">Categories</Link></li>
- [ ] The navbar menu doesn't match the Figma design. Kindly match the font color. :+1: 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![your1](https://user-images.githubusercontent.com/70483835/222631020-93a21a12-acf6-4894-aa73-2d226cfc321a.png) | ![figma1](https://user-images.githubusercontent.com/70483835/222631478-59160a74-3cb8-49cd-b231-8551f9821674.png)

2023-03-03 04:57 UTC, julie-ify approved these changes
Hi @gsmalik030,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 06:59 UTC, merged